// src/views/AnalyticsView.svelte
<script>
	import Chart from '../components/Chart.svelte';
	import Notification from '../components/Notification.svelte';

	export let active;

	let theme = 'light';
</script>

<main hidden={!active}>
	<section class="analytics">
		<Notification type="info">Esta sección provee información sobre diferentes métricas de uso y rendimiento del chat en el tiempo, representadas como gráficos.</Notification>
		<br />

		<center>
			<Chart id="98de19e7-41b0-4c03-b0d5-a8544e23563d" theme={theme} />
			<br />
			<Chart id="5be1e0cb-70c1-481f-9a7a-0b80d2477ef7" theme={theme} />
			<br />
			<Chart id="1ae95d7f-0f87-4fc9-9b33-0dfe2a7fa85a" thene={theme} />
			<br />
			<Chart id="350f22d4-ae63-4cf8-a222-d36df924ff0c" theme={theme} />
			<br />
		</center>
	</section>
</main>

// src/views/AnalyticsView.vue
<template>
  <section class="AnalyticsView">
    <Notification type="info">Esta sección provee información sobre métricas de uso del chat, representadas como gráficos.</Notification>
    <Chart name="messages-last-30-days" chartId="98de19e7-41b0-4c03-b0d5-a8544e23563d" />
  </section>
</template>

<script>
  import Notification from '../components/Notification.vue';
  import Chart from '../components/Chart.vue';

  export default {
    name: 'AnalyticsView',
    components: {
      Chart,
      Notification
    },
    data() {
      return {
      }
    }
  }
</script>
