// src/views/LiveChatView.vue
<template>
  <section class="LiveChatView">
    <Notification type="info">Los nuevos mensajes aparecerán en tiempo real en esta página.</Notification>
    <hr>
    <div class="interface-options">
      <label class="label">
      <input class="checkbox" type="checkbox" v-model="uiState.compactMode">
      Modo compacto (útil al copiar varios mensajes)
      </label>
    </div>
    <hr>
    <ul class="entries">
      <li v-for="entry in liveMessages">
        <CompactMessage v-if="uiState.compactMode" v-bind="entry" />
        <template v-else>
          <ChatMessage
          v-if="entry.event === 'MESSAGE' || entry.event === 'ME'"
          :username="entry.user"
          :timestamp="entry.timestamp"
          :message="entry.text"
          :isRoleplay="entry.event === 'ME'"
          :deleted="entry.deleted"
          :deletionReason="entry.deletionReason"
          />
          <SystemMessage v-else v-bind="entry" />
        </template>
      </li>
    </ul>
  </section>
</template>

<script>
  import ChatMessage from '../components/ChatMessage.vue';
  import SystemMessage from '../components/SystemMessage.vue';
  import CompactMessage from '../components/CompactMessage.vue';

  export default {
    name: 'LiveChatView',
    components: {
      ChatMessage,
      SystemMessage,
      CompactMessage
    },
    mounted() {
      const messageService = this.$feathers.service('entries');
      messageService.on('created', (message) => {
        if (import.meta.env.DEV) console.log('Message created: ', message);
        this.liveMessages.push(message);
      });
    },
    data() {
      return {
        liveMessages: [],
        uiState: {
          compactMode: false
        }
      }
    }
  }
</script>

// src/views/LiveChatView.svelte
<script>
	import ChatMessage from '../components/ChatMessage.svelte';
	import SystemMessage from '../components/SystemMessage.svelte';
	import CompactMessage from '../components/CompactMessage.svelte';
	import Notification from '../components/Notification.svelte';

	export let client, active;

	const messageService = client.service('entries');
	let uiState = {
		// display options
		compactMode: false
	};

	let entries = [];

	messageService.on('created', (message) => {
		console.log('Message created:', message);
		entries = [...entries, message];
	});
</script>

<main hidden={!active}>
	<section class="liveChat">
		<Notification type="info">Los nuevos eventos de chat aparecerán en tiempo real en esta página.</Notification>
		<hr>
		<div class="interface-options">
			<label class="label">
			<input class="checkbox" type="checkbox" bind:checked={uiState.compactMode}>
			Modo compacto (útil al copiar varios mensajes)
			</label>
		</div>
		<hr>
		<div class="entries">
			{#each entries as entry}
				{#if uiState.compactMode}
					<CompactMessage {...entry}/>
				{:else}
					{#if entry.event === 'MESSAGE'}
						<ChatMessage
							username={entry.user}
							timestamp={entry.timestamp}
							message={entry.text}
							isRoleplay={false} />
					{:else if entry.event === 'ME'}
						<ChatMessage
							username={entry.user}
							timestamp={entry.timestamp}
							message={entry.text}
							isRoleplay={true} />
					{:else}
						<SystemMessage {...entry} />
					{/if}				
				{/if}
			{/each}
		</div>
	</section>
</main>
