// src/components/Footer.vue
<template>
  <footer class="footer">
    <div class="content has-text-centered">
      <p>
        <em>El contenido presentado aquí es propiedad de la comunidad de Steven Universe Wiki. Para solicitar la eliminación de contenidos, contactarse con la <a href="https://steven-universe.fandom.com/es/wiki/Steven_Universe_Wiki:Administradores" target="_blank" rel="noopener">administración del sitio</a>.</em>
      </p>
      <p>
        <strong>SUW-Logs</strong> - using yves {{version}} - Style: <a href="https://bulma.io/" target="_blank" rel="noopener">Bulma CSS</a>.
      </p>
    </div>
  </footer>
</template>

<script>
export default {
  name: 'Footer',
  data() {
    return {
      version: import.meta.env.VITE_YVES_VERSION
    }
  }
}
</script>

<style scoped>
  .footer {
    padding: 2rem 1.5rem 1rem;
  }
</style>

// src/components/Footer.svelte
<script>
	const version = import.meta.env.VITE_YVES_VERSION;
</script>

<footer class="footer">
	<div class="content has-text-centered">
		<p>
			<em>El contenido presentado aquí es propiedad de la comunidad de Steven Universe Wiki. Para solicitar la eliminación de contenidos, contactarse con la <a href="https://steven-universe.fandom.com/es/wiki/Steven_Universe_Wiki:Administradores" target="_blank" rel="noopener">administración del sitio</a>.</em>
		</p>
		<p>
			<strong>SUW-Logs</strong> - using yves {version} - Style: <a href="https://bulma.io/" target="_blank" rel="noopener">Bulma CSS</a>.
		</p>
	</div>
</footer>

<style>
	.footer {
		padding: 2rem 1.5rem 1rem;
	}
</style>
