// src/components/SystemMessage.svelte
<script>
	import { beforeUpdate } from 'svelte';
	import { addMinutes, addSeconds, lightFormat, formatDistance } from 'date-fns';
	import { es } from 'date-fns/locale';
	
	export let event, user, timestamp, targetUser, banLength, banReason, deleted, deletionReason;

	let banExpiry;
	beforeUpdate(() => {
		if (event === 'BAN') banExpiry = addSeconds(new Date(timestamp), banLength);
	});
</script>

<main>
	<div class="system-message media message is-half">
		<div class="media-content message-text">
			<small>[{lightFormat(addMinutes(new Date(timestamp), new Date(timestamp).getTimezoneOffset()), "dd/MM/yyyy, h:mm:ss aa", {
				    	locale: es
				    })}]</small>
			{#if deleted}
				<ion-icon name="trash"></ion-icon> <i>Este elemento ha sido eliminado. Razón: {deletionReason}</i>
			{:else}
				{#if event === 'JOIN'}
					{user} ha entrado al chat.
				{:else if event === 'PART'}
					{user} ha salido del chat.
				{:else if event === 'KICK'}
					{targetUser} fue expulsado por {user}.
				{:else if event === 'BAN'}
					{targetUser} fue baneado por {user} durante {formatDistance(banExpiry, new Date(timestamp), {
						locale: es
					})}  (razón: {banReason || 'no especificada'}).
				{:else if event === 'UNBAN'}
					{user} revocó el ban de {targetUser} (razón: {banReason || 'no especificada'}).
				{/if}
			{/if}
		</div>
	</div>
</main>

<style type="text/css">
	.system-message {
		text-align: center;
		margin-top: 10px;
		margin-bottom: 10px;
	}
	.system-message .message-text {
		text-align: center;
		padding: 6px;
		border-radius: 6px;
	}
	
</style>

// src/components/SystemMessage.vue
<template>
  <article class="system-message media message is-half">
    <div class="media-content message-text">
      <small> [{{formattedTimestamp}}] </small>
      <template v-if="deleted">
        <ion-icon name="trash" /> <em>[Este elemento ha sido eliminado. Razón: {{deletionReason}}]</em>
      </template>
      <template v-else>
        <template v-if="event === 'JOIN'">
          ~ {{user}} ha entrado al chat. ~
        </template>
        <template v-else-if="event === 'PART'">
          ~ {{user}} ha salido del chat. ~
        </template>
        <template v-else-if="event === 'KICK'">
          ~ {{targetUser}} fue expulsado por {{user}}. ~
        </template>
        <template v-else-if="event === 'BAN'">
          ~ {{targetUser}} fue baneado por {{user}} durante {{formattedBanLength}} (razón: {{banReason || 'no especificada'}}). ~
        </template>
        <template v-else-if="event === 'UNBAN'">
          ~ {{user}} revocó el ban de {{targetUser}} (razón: {{banReason || 'no especificada'}}). ~
        </template>
      </template>
    </div>
  </article>
</template>

<script>
  import { addMinutes, addSeconds, lightFormat, formatDistance } from 'date-fns';
  import { es } from 'date-fns/locale';

  export default {
    name: 'SystemMessage',
    props: {
      event: String,
      user: String,
      timestamp: String,
      targetUser: String,
      banLength: Number,
      banReason: String,
      deleted: Boolean,
      deletionReason: String
    },
    data() {
      return {
        banExpiry: null
      }
    },
    beforeUpdate() {
      if (this.event === 'BAN')
        this.banExpiry = addSeconds(new Date(this.timestamp), this.banLength);
    },
    computed: {
      formattedTimestamp() {
        return lightFormat(addMinutes(new Date(this.timestamp), new Date(this.timestamp).getTimezoneOffset()), "dd/MM/yyyy, h:mm:ss aa", {
          locale: es
        });
      },
      formattedBanLength() {
        if (!this.banLength) return 0;
        return formatDistance(new Date(this.banExpiry), new Date(this.timestamp), {
          locale: es
        });
      }
    }
  }
</script>

<style scoped>
  .system-message {
    text-align: center;
    margin-top: 10px;
    margin-bottom: 10px;
  }
  .system-message .message-text {
    text-align: center;
    padding: 6px;
    border-radius: 6px;
  }
</style>
