// src/App.vue
<template>
  <Navbar title="Registros de chat" />
  <section class="section">
    <div class="container">
      <div class="tabs is-fullwidth">
        <ul>
          <li :class="{'is-active': activeTab === 'logs'}">
            <a @click="switchTab('logs')">
              <span class="icon is-small"><ion-icon name="document-text-outline" /></span>
              <span>Buscar mensajes</span>
            </a>
          </li>
          <li :class="{'is-active': activeTab === 'live-chat'}">
            <a @click="switchTab('live-chat')">
              <span class="icon is-small"><ion-icon name="chatbubbles-outline" /></span>
              <span>Chat en directo</span>
            </a>
          </li>
          <li :class="{'is-active': activeTab === 'event-stats'}">
            <a @click="switchTab('event-stats')">
              <span class="icon is-small"><ion-icon name="star-outline" /></span>
              <span>Evento</span>
            </a>
          </li>
          <li :class="{'is-active': activeTab === 'analytics'}">
            <a @click="switchTab('analytics')">
              <span class="icon is-small"><ion-icon name="analytics-outline" /></span>
              <span>Estadísticas</span>
            </a>
          </li>
        </ul>
      </div>
      <LogSearchView v-show="activeTab === 'logs'"/>
      <LiveChatView v-show="activeTab === 'live-chat'" />
      <EventStatsView v-show="activeTab === 'event-stats'" />
      <AnalyticsView v-if="analyticsLoaded" v-show="activeTab === 'analytics'" />
    </div>
  </section>
  <Footer />
</template>

<script>
  import LogSearchView from './views/LogSearchView.vue';
  import LiveChatView from './views/LiveChatView.vue';
  import EventStatsView from './views/EventStatsView.vue';
  import AnalyticsView from './views/AnalyticsView.vue';

  import Navbar from './components/Navbar.vue';
  import Footer from './components/Footer.vue';

  export default {
    name: 'App',
    components: {
      Navbar,
      Footer,
      LogSearchView,
      LiveChatView,
      EventStatsView,
      AnalyticsView
    },
    data() {
      return {
        activeTab: 'logs',
        analyticsLoaded: false
      }
    },
    methods: {
      switchTab(tabName) {
        if (tabName === 'analytics' && !this.analyticsLoaded) {
          this.analyticsLoaded = true;
        }
        this.activeTab = tabName;
      }
    }
  }
</script>

// src/App.svelte
<script>
  // components
  import Navbar from './components/Navbar.svelte';
  import Footer from './components/Footer.svelte';

  // children views
  import LogSearchView from './views/LogSearchView.svelte';
  import LiveChatView from './views/LiveChatView.svelte';
  import AnalyticsView from './views/AnalyticsView.svelte';

  import io from 'socket.io-client';
  import feathers from '@feathersjs/feathers';
  import socketio from '@feathersjs/socketio-client';

  const socket = io(import.meta.env.DEV ? 'http://localhost:3030': import.meta.env.VITE_YVES_API);
  const client = feathers();
  client.configure(socketio(socket));

  let currentTab = 'logs';
  let analyticsTabLoaded = false;
</script>

<main>
  <Navbar title="Registros de chat"/>
  <section class="section">
  <div class="container">
  <div class="tabs is-fullwidth">
    <ul>
      <li class:is-active="{currentTab === 'logs'}" on:click="{() => currentTab = 'logs' }">
        <a>
          <span class="icon is-small"><ion-icon name="document-text-outline"></ion-icon></span>
          <span>Buscar mensajes</span>
        </a>
      </li>
      <li class:is-active="{currentTab === 'live-chat'}" on:click="{() => currentTab = 'live-chat' }">
        <a>
          <span class="icon is-small"><ion-icon name="chatbubbles-outline"></ion-icon></span>
          <span>Chat en directo</span>
        </a>
      </li>
      <li class:is-active="{currentTab === 'analytics'}" on:click="{() => { currentTab = 'analytics'; analyticsTabLoaded = true }}">
        <a>
          <span class="icon is-small"><ion-icon name="analytics-outline"></ion-icon></span>
          <span>Estadísticas</span>
        </a>
      </li>
    </ul>
  </div>
  <LogSearchView client={client} active={currentTab === 'logs'} />
  <LiveChatView client={client} active={currentTab === 'live-chat'} />
  {#if analyticsTabLoaded}
    <AnalyticsView active={currentTab === 'analytics'} />
  {/if}
</div>
</section>
<Footer/>
</main>

<style>
  .section {
    padding: 0.8rem 1.5rem;
  }

  .tabs {
    margin-top: 10px;
  }
</style>
